### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by yoiyami96** [Special-Week/nonebot_plugin_BitTorrent#13]
06-19 11:40:09 [ERROR] nonebot | Failed to import "nonebot_plugin_BitTorrent"
Traceback (most recent call last):
  File "<string>", line 14, in <module>
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\plugin\load.py", line 125, in load_from_toml
    return load_all_plugins(plugins, plugin_dirs)
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\plugin\load.py", line 62, in load_all_plugins
    return manager.load_all_plugins()
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\plugin\manager.py", line 175, in load_all_plugins
    return set(
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\plugin\manager.py", line 176, in <genexpr>
    filter(None, (self.load_plugin(name) for name in self.available_plugins))
> File "C:\Users\cyy19\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\plugin\manager.py", line 141, in load_plugin
    module = importlib.import_module(name)
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot\plugin\manager.py", line 240, in exec_module
    super().exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\cyy19\AppData\Local\Programs\Python\Python311\Lib\site-packages\nonebot_plugin_BitTorrent\__init__.py", line 9, in <module>
    __plugin_meta__ = PluginMetadata(
TypeError: PluginMetadata.__init__() got an unexpected keyword argument 'type'

**Comment by Special-Week** [comment]
更新你的nonebot2，或者手动把__plugin_meta__注释掉，plugin_meta是nonebot2 2.0.0商店插件的强制要求
